name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint python-dotenv
        pip install streamlit duckduckgo-search requests openai beautifulsoup4
        pip install "gql[requests]"
        # Try to install swarm, but don't fail if it doesn't work
        pip install git+https://github.com/openai/swarm.git@main || \
        pip install swarm-framework || \
        echo "Warning: Could not install swarm package, pylint will disable import errors"
    - name: Check file names
      run: |
        python .github/workflows/check_file_names.py
    - name: Analyse the code with pylint
      run: |
        pylint $(git ls-files '*.py') --disable=import-error --fail-under=8.0
